#:schema node_modules/wrangler/config-schema.json
name = "portfolio-bucket-worker"
main = "src/index.ts"
compatibility_date = "2024-10-04"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#r2-buckets
[[r2_buckets]]
binding = "PORTFOLIO_BUCKET"
bucket_name = "portfolio-bucket"
preview_bucket_name="preview-portfolio-bucket"

[vars]
ENVIRONMENT = "production"